apiVersion: automation.cloudbees.io/v1alpha1
name: trigger-publish-test-results-action
kind: workflow

on:
  push:
    branches:
      - main

jobs:
  Junit-Test:
    steps:
      - name: checkout-source-code
        uses: cloudbees-io/checkout@v1

      - name: Install gotestsum and Run Tests
        uses: docker://golang:latest
        run: |
          go install gotest.tools/gotestsum@latest
          export PATH=$PATH:$(go env GOPATH)/bin
          mkdir -p test-results
          gotestsum --junitfile test-results/test-report.xml
          cat test-results/test-report.xml

      # - name: Print Test Results XML
      #   run: cat test-results/test-report.xml

      - name: GO
        uses: cloudbees-io/publish-test-results@v1
        with:
          test-type: go
          folder-name: ${{ cloudbees.workspace }}/test-results/test-report.xml
